version: '2.4'
services:
 dns:
  container_name: coredns
  image: coredns/coredns
  ports:
   - '53:53/udp'  
  restart: always
  privileged: true
  cpu_count: 1
  cpu_percent: 20
  cpus: 0.1
  mem_limit: 1000000000
  mem_reservation: 200m
  entrypoint: 
   - '/coredns'
   - '-conf'
   - '/etc/coredns/Corefile'
