version: '3.7'
services:
 dns:
  container_name: coredns
  image: coredns/coredns
  ports:
   - '53:53/udp'
  volumes:
   - /home/debashish/coredns/Corefile:/etc/coredns/Corefile
  restart: always
  privileged: true
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 250M
      reservations:
        cpus: '0.25'
        memory: 20M
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
  entrypoint: 
   - '/coredns'
   - '-conf'
   - '/etc/coredns/Corefile'
   
  
 app:
  depends_on:
   - dns
  container_name: home-assistant
  image: homeassistant/home-assistant
  ports:
   - '8123:8123'
  volumes:
   - '/etc/localtime:/etc/localtime:ro'
  restart: always
  dns:
   0.0.0.0
    